$ErrorActionPreference = "SilentlyContinue"
mkdir public/logos -Force
Write-Host "Downloading SiteGround..."
curl -o "public/logos/siteground.png" "https://www.google.com/s2/favicons?domain=siteground.com&sz=128"
Write-Host "Downloading HostGator..."
curl -o "public/logos/hostgator.png" "https://www.google.com/s2/favicons?domain=hostgator.com&sz=128"
Write-Host "Downloading Bluehost..."
curl -o "public/logos/bluehost.png" "https://www.google.com/s2/favicons?domain=bluehost.com&sz=128"
Write-Host "Downloading WP Engine..."
curl -o "public/logos/wp_engine.png" "https://www.google.com/s2/favicons?domain=wpengine.com&sz=128"
Write-Host "Downloading CloudFront..."
curl -o "public/logos/cloudfront.png" "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=128"
Write-Host "Downloading BritBox..."
curl -o "public/logos/britbox.png" "https://www.google.com/s2/favicons?domain=britbox.com&sz=128"
Write-Host "Downloading Acorn TV..."
curl -o "public/logos/acorn_tv.png" "https://www.google.com/s2/favicons?domain=acorn.tv&sz=128"
Write-Host "Downloading Viki..."
curl -o "public/logos/viki.png" "https://www.google.com/s2/favicons?domain=viki.com&sz=128"
Write-Host "Downloading Fabletics..."
curl -o "public/logos/fabletics.png" "https://www.google.com/s2/favicons?domain=fabletics.com&sz=128"
Write-Host "Downloading Savage X Fenty..."
curl -o "public/logos/savage_x_fenty.png" "https://www.google.com/s2/favicons?domain=savagex.com&sz=128"
Write-Host "Downloading Minecraft Realms..."
curl -o "public/logos/minecraft_realms.png" "https://www.google.com/s2/favicons?domain=minecraft.net&sz=128"
Write-Host "Downloading RuneScape..."
curl -o "public/logos/runescape.png" "https://www.google.com/s2/favicons?domain=runescape.com&sz=128"
Write-Host "Downloading World of Warcraft..."
curl -o "public/logos/world_of_warcraft.png" "https://www.google.com/s2/favicons?domain=blizzard.com&sz=128"
Write-Host "Downloading FFXIV Sub..."
curl -o "public/logos/ffxiv_sub.png" "https://www.google.com/s2/favicons?domain=finalfantasyxiv.com&sz=128"
Write-Host "Downloading Substack..."
curl -o "public/logos/substack.png" "https://www.google.com/s2/favicons?domain=substack.com&sz=128"
Write-Host "Downloading Morning Brew..."
curl -o "public/logos/morning_brew.png" "https://www.google.com/s2/favicons?domain=morningbrew.com&sz=128"
Write-Host "Downloading Zapier..."
curl -o "public/logos/zapier.png" "https://www.google.com/s2/favicons?domain=zapier.com&sz=128"
Write-Host "Downloading Airtable..."
curl -o "public/logos/airtable.png" "https://www.google.com/s2/favicons?domain=airtable.com&sz=128"
Write-Host "Downloading Webflow..."
curl -o "public/logos/webflow.png" "https://www.google.com/s2/favicons?domain=webflow.com&sz=128"
Write-Host "Downloading Framer..."
curl -o "public/logos/framer.png" "https://www.google.com/s2/favicons?domain=framer.com&sz=128"
Write-Host "Downloading Linear..."
curl -o "public/logos/linear.png" "https://www.google.com/s2/favicons?domain=linear.app&sz=128"
Write-Host "Downloading Spectrum..."
curl -o "public/logos/spectrum.png" "https://www.google.com/s2/favicons?domain=spectrum.com&sz=128"
Write-Host "Downloading Cox..."
curl -o "public/logos/cox.png" "https://www.google.com/s2/favicons?domain=cox.com&sz=128"
Write-Host "Downloading DirecTV..."
curl -o "public/logos/directv.png" "https://www.google.com/s2/favicons?domain=directv.com&sz=128"
Write-Host "Downloading Dish Network..."
curl -o "public/logos/dish_network.png" "https://www.google.com/s2/favicons?domain=dish.com&sz=128"
Write-Host "Downloading Vercel..."
curl -o "public/logos/vercel.png" "https://www.google.com/s2/favicons?domain=vercel.com&sz=128"
Write-Host "Downloading Netlify..."
curl -o "public/logos/netlify.png" "https://www.google.com/s2/favicons?domain=netlify.com&sz=128"
Write-Host "Downloading JetBrains..."
curl -o "public/logos/jetbrains.png" "https://www.google.com/s2/favicons?domain=jetbrains.com&sz=128"
Write-Host "Downloading Render..."
curl -o "public/logos/render.png" "https://www.google.com/s2/favicons?domain=render.com&sz=128"
Write-Host "Downloading Fly.io..."
curl -o "public/logos/fly_io.png" "https://www.google.com/s2/favicons?domain=fly.io&sz=128"
Write-Host "Downloading Sentry..."
curl -o "public/logos/sentry.png" "https://www.google.com/s2/favicons?domain=sentry.io&sz=128"
Write-Host "Downloading Datadog..."
curl -o "public/logos/datadog.png" "https://www.google.com/s2/favicons?domain=datadoghq.com&sz=128"
Write-Host "Downloading 1Password..."
curl -o "public/logos/1password.png" "https://www.google.com/s2/favicons?domain=1password.com&sz=128"
Write-Host "Downloading LastPass..."
curl -o "public/logos/lastpass.png" "https://www.google.com/s2/favicons?domain=lastpass.com&sz=128"
Write-Host "Downloading Dashlane..."
curl -o "public/logos/dashlane.png" "https://www.google.com/s2/favicons?domain=dashlane.com&sz=128"
Write-Host "Downloading Bitwarden..."
curl -o "public/logos/bitwarden.png" "https://www.google.com/s2/favicons?domain=bitwarden.com&sz=128"
Write-Host "Downloading The New Yorker..."
curl -o "public/logos/the_new_yorker.png" "https://www.google.com/s2/favicons?domain=newyorker.com&sz=128"
Write-Host "Downloading The Atlantic..."
curl -o "public/logos/the_atlantic.png" "https://www.google.com/s2/favicons?domain=theatlantic.com&sz=128"
Write-Host "Downloading Wired..."
curl -o "public/logos/wired.png" "https://www.google.com/s2/favicons?domain=wired.com&sz=128"
Write-Host "Downloading Bloomberg..."
curl -o "public/logos/bloomberg.png" "https://www.google.com/s2/favicons?domain=bloomberg.com&sz=128"
Write-Host "Downloading Financial Times..."
curl -o "public/logos/financial_times.png" "https://www.google.com/s2/favicons?domain=ft.com&sz=128"
Write-Host "Downloading Headspace..."
curl -o "public/logos/headspace.png" "https://www.google.com/s2/favicons?domain=headspace.com&sz=128"
Write-Host "Downloading Calm..."
curl -o "public/logos/calm.png" "https://www.google.com/s2/favicons?domain=calm.com&sz=128"
Write-Host "Downloading Noom..."
curl -o "public/logos/noom.png" "https://www.google.com/s2/favicons?domain=noom.com&sz=128"
Write-Host "Downloading WeightWatchers..."
curl -o "public/logos/weightwatchers.png" "https://www.google.com/s2/favicons?domain=weightwatchers.com&sz=128"
Write-Host "Downloading Whoop..."
curl -o "public/logos/whoop.png" "https://www.google.com/s2/favicons?domain=whoop.com&sz=128"
Write-Host "Downloading X Premium (Twitter)..."
curl -o "public/logos/x_premium__twitter_.png" "https://www.google.com/s2/favicons?domain=twitter.com&sz=128"
Write-Host "Downloading Feeld..."
curl -o "public/logos/feeld.png" "https://www.google.com/s2/favicons?domain=feeld.co&sz=128"
Write-Host "Downloading Her..."
curl -o "public/logos/her.png" "https://www.google.com/s2/favicons?domain=weareher.com&sz=128"
Write-Host "Downloading GoFundMe..."
curl -o "public/logos/gofundme.png" "https://www.google.com/s2/favicons?domain=gofundme.com&sz=128"
Write-Host "Downloading ActBlue..."
curl -o "public/logos/actblue.png" "https://www.google.com/s2/favicons?domain=actblue.com&sz=128"
Write-Host "Downloading WinRed..."
curl -o "public/logos/winred.png" "https://www.google.com/s2/favicons?domain=winred.com&sz=128"
Write-Host "Downloading Ko-fi..."
curl -o "public/logos/ko_fi.png" "https://www.google.com/s2/favicons?domain=ko-fi.com&sz=128"
Write-Host "Downloading Twilio..."
curl -o "public/logos/twilio.png" "https://www.google.com/s2/favicons?domain=twilio.com&sz=128"
Write-Host "Downloading Zoom Phone..."
curl -o "public/logos/zoom_phone.png" "https://www.google.com/s2/favicons?domain=zoom.us&sz=128"
Write-Host "Downloading OpenCNAM..."
curl -o "public/logos/opencnam.png" "https://www.google.com/s2/favicons?domain=opencnam.com&sz=128"
Write-Host "Downloading Box..."
curl -o "public/logos/box.png" "https://www.google.com/s2/favicons?domain=box.com&sz=128"
Write-Host "Downloading OneDrive..."
curl -o "public/logos/onedrive.png" "https://www.google.com/s2/favicons?domain=microsoft.com&sz=128"
Write-Host "Downloading ClassPass..."
curl -o "public/logos/classpass.png" "https://www.google.com/s2/favicons?domain=classpass.com&sz=128"
Write-Host "Downloading Carbonite..."
curl -o "public/logos/carbonite.png" "https://www.google.com/s2/favicons?domain=carbonite.com&sz=128"
Write-Host "Downloading Backblaze..."
curl -o "public/logos/backblaze.png" "https://www.google.com/s2/favicons?domain=backblaze.com&sz=128"
Write-Host "Downloading ProtonMail..."
curl -o "public/logos/protonmail.png" "https://www.google.com/s2/favicons?domain=proton.me&sz=128"
Write-Host "Downloading Fastmail..."
curl -o "public/logos/fastmail.png" "https://www.google.com/s2/favicons?domain=fastmail.com&sz=128"
Write-Host "Downloading Name.com..."
curl -o "public/logos/name_com.png" "https://www.google.com/s2/favicons?domain=name.com&sz=128"
